# Generated by Django 3.1 on 2020-08-27 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_framework_test_app', '0002_auto_20200810_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttribute2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('user_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='more', to='graphql_framework_test_app.userattribute')),
            ],
        ),
    ]
